// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sudoku.API.DbContexts;

#nullable disable

namespace Sudoku.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230312143801_AddSudokuModelToDB")]
    partial class AddSudokuModelToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sudoku.API.Models.Sudoku", b =>
                {
                    b.Property<int>("SudokuHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SudokuHistoryId"));

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SolvedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SudokuHistoryId");

                    b.ToTable("Sudokus");
                });
#pragma warning restore 612, 618
        }
    }
}
